NetCoreRedis.Web.StackExchangeAPI/Models/ErrorViewModel.cs
using System;

namespace NetCoreRedis.Web.StackExchangeAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreRedis.Web.StackExchangeAPI.Services;
using StackExchange.Redis;
using System.Collections.Generic;
using System.Linq;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class HashTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        private string listName = "dictionaries";

        public HashTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(4);
        }

        public IActionResult Index()
        {
            var dictionary = new Dictionary<string,string>();
            if (db.KeyExists(listName))
            {
                db.HashGetAll(listName).ToList().ForEach(x =>
                {
                    dictionary.Add(x.Name.ToString(),x.Value.ToString());
                });
            }
            return View(dictionary);
        }

        [HttpPost]
        public IActionResult Add(string key,string value)
        {
            db.HashSet(listName,key,value);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string key)
        {
            db.HashDelete(listName,key);
            return RedirectToAction(nameof(Index));
        }
    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NetCoreRedis.Web.StackExchangeAPI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreRedis.Web.StackExchangeAPI.Services;
using StackExchange.Redis;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        private string listName = "meyve";

        public ListTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(1);
        }

        public IActionResult Index()
        {
            var nameList = new List<string>();
            if(db.KeyExists(listName))
            {
                db.ListRange(listName).ToList().ForEach(x=>
                {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            db.ListRightPush(listName, name);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remove(string name)
        {
            await db.ListRemoveAsync(listName, name).ConfigureAwait(false); 
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteFirstItem()
        {
            db.ListLeftPop(listName);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteLastItem()
        {
            db.ListRightPop(listName);
            return RedirectToAction(nameof(Index));
        }
    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreRedis.Web.StackExchangeAPI.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class SetTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        private string listName = "hashset";

        public SetTypeController(RedisService redis)
        {
            _redis = redis;
            this.db = _redis.GetDb(2);
        }

        public IActionResult Index()
        {
            var nameList = new HashSet<string>();
            if (db.KeyExists(listName))
            {
                db.SetMembers(listName).ToList().ForEach(x=>
                {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            //if(!db.KeyExists(listName))
            //{
            db.KeyExpire(listName, DateTime.Now.AddMinutes(5));
            //}
            db.SetAdd(listName, name);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteItem(string name)
        {
            db.SetRemove(listName, name);
            return RedirectToAction(nameof(Index));
        }

    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/SortedSetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreRedis.Web.StackExchangeAPI.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class SortedSetTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        private string listName = "sortedset";

        public SortedSetTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(3);
        }

        public IActionResult Index()
        {
            var nameList = new SortedSet<string>();
            if (db.KeyExists(listName))
            {
                //İki kodun işlevi aynıdır tek farkı ilk komutta score ve element alınabiliyorken diğerinde sadece element değeri geliyor.
                db.SortedSetScan(listName).ToList().ForEach(x =>
                {
                    nameList.Add(x.Element.ToString());
                });

                //db.SortedSetRangeByRank(listName,order:Order.Ascending).ToList().ForEach(x =>
                //{
                //    nameList.Add(x.ToString());
                //});
            }
            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name, int score)
        {
            db.KeyExpire(listName, DateTime.Now.AddMinutes(1));
            db.SortedSetAdd(listName, name, score);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string name)
        {
            db.SortedSetRemove(listName, name);
            return RedirectToAction(nameof(Index));
        }
    }
}

NetCoreRedis.Web.StackExchangeAPI/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreRedis.Web.StackExchangeAPI.Services;
using StackExchange.Redis;

namespace NetCoreRedis.Web.StackExchangeAPI.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase db;
        public StringTypeController(RedisService redis)
        {
            _redis = redis;
            db = _redis.GetDb(0);
        }

        public IActionResult Index()
        {
            db.StringSet("name", "salihavci.com * blog");
            db.StringSet("job", "dotnet developer");
            return View();
        }

        public IActionResult Show()
        {
            //var valueCharSubstring = db.StringGetRange("gamer", 0, 3);
            //var length = db.StringLength("name");
            //var image = db.StringSet("resim", new byte[] { });
            var value = db.StringGet("job");
            //var count = db.StringIncrement("counter", 1); //counter++
            if(value.HasValue)
            {
                ViewBag.value = value.ToString();
            }
            return View();
        }
    }
}

NetCoreRedis.Web.StackExchangeAPI/Views/HashType/Index.cshtml
@model Dictionary<string,string>
@{
    ViewData["Title"] = "Index";
}

<form asp-action="Add" asp-controller="HashType" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label for="name" class="col-form-label">Key</label>
        <input type="text" name="key" class="form-control" />
    </div>
    <div class="form-group">
        <label for="name" class="col-form-label">Value</label>
        <input type="text" name="value" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
</form>

@foreach (var item in Model)
{

    <h2>@item.Key -> @item.Value <a asp-controller="HashType" asp-action="Remove" asp-route-key="@item.Key" class="btn btn-danger">Sil</a></h2>
}

NetCoreRedis.Web.StackExchangeAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreRedis.Web.StackExchangeAPI/Views/SetType/Index.cshtml
@model HashSet<string>
@{
    ViewData["Title"] = "Index";
}

<form asp-action="Add" asp-controller="SetType" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label for="name" class="col-form-label">Name</label>
        <input type="text" name="name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
</form>

@foreach (var item in Model)
{
    <h2>@item <a asp-controller="SetType" asp-action="Remove" asp-route-name="@item" class="btn btn-danger">Sil</a></h2>
}

NetCoreRedis.Web.StackExchangeAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreRedis.Web.StackExchangeAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreRedis.Web.StackExchangeAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetCoreRedis.Web.StackExchangeAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetCoreRedis.Web.StackExchangeAPI/Views/SortedSetType/Index.cshtml
@model SortedSet<string>
@{
    ViewData["Title"] = "Index";
}

<form asp-action="Add" asp-controller="SortedSetType" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label for="name" class="col-form-label">Name</label>
        <input type="text" name="name" class="form-control" />
    </div>
    <div class="form-group">
        <label for="name" class="col-form-label">Score</label>
        <input type="number" name="score" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
</form>

@foreach (var item in Model)
{
    <h2>@item <a asp-controller="SortedSetType" asp-action="Remove" asp-route-name="@item" class="btn btn-danger">Sil</a></h2>
}

NetCoreRedis.Web.StackExchangeAPI/Views/StringType/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

NetCoreRedis.Web.StackExchangeAPI/Views/StringType/Show.cshtml
@{
    ViewData["Title"] = "Show";
}

<h1>@ViewBag.value</h1>